<a href="https://colab.research.google.com/github/Debasmita-Pal/Single_Layer_Perceptron/blob/main/20MAI0018_ASS1_QS2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
path = 

# Install the PyDrive wrapper & import libraries.
# This only needs to be done once per notebook.
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

file_id = '1Qjiv7gppEn2Mua862PMuX02YTVNLUCxL'
downloaded = drive.CreateFile({'id': file_id})

In [24]:
downloaded.GetContentFile('seeds_dataset.xlsx')

In [25]:
!ls -lha seeds_dataset.xlsx

-rw-r--r-- 1 root root 21K Feb 25 07:39 seeds_dataset.xlsx


In [26]:
!pip install -q xlrd

import pandas as pd
df = pd.read_excel('seeds_dataset.xlsx')
df

15.260  14.840  0.871   5.763   3.312   2.221   5.220   1.000 
0     14.88   14.57  0.8811   5.554   3.333   1.018   4.956       1
1     14.29   14.09  0.9050   5.291   3.337   2.699   4.825       1
2     13.84   13.94  0.8955   5.324   3.379   2.259   4.805       1
3     16.14   14.99  0.9034   5.658   3.562   1.355   5.175       1
4     14.38   14.21  0.8951   5.386   3.312   2.462   4.956       1
..      ...     ...     ...     ...     ...     ...     ...     ...
204   12.19   13.20  0.8783   5.137   2.981   3.631   4.870       3
205   11.23   12.88  0.8511   5.140   2.795   4.325   5.003       3
206   13.20   13.66  0.8883   5.236   3.232   8.315   5.056       3
207   11.84   13.21  0.8521   5.175   2.836   3.598   5.044       3
208   12.30   13.34  0.8684   5.243   2.974   5.637   5.063       3

[209 rows x 8 columns]

In [27]:
import numpy as np
print(df.head())
print(df.info())


   15.260  14.840  0.871   5.763   3.312   2.221   5.220   1.000 
0   14.88   14.57  0.8811   5.554   3.333   1.018   4.956       1
1   14.29   14.09  0.9050   5.291   3.337   2.699   4.825       1
2   13.84   13.94  0.8955   5.324   3.379   2.259   4.805       1
3   16.14   14.99  0.9034   5.658   3.562   1.355   5.175       1
4   14.38   14.21  0.8951   5.386   3.312   2.462   4.956       1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   15.26   209 non-null    float64
 1   14.84   209 non-null    float64
 2   0.871   209 non-null    float64
 3   5.763   209 non-null    float64
 4   3.312   209 non-null    float64
 5   2.221   209 non-null    float64
 6   5.22    209 non-null    float64
 7   1.0     209 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 13.2 KB
None


In [28]:
df.shape

(209, 8)

In [31]:
varnames=['A'+str(s) for s in range(1,9)]
df.columns=varnames
df.head(5)

A1     A2      A3     A4     A5     A6     A7  A8
0  14.88  14.57  0.8811  5.554  3.333  1.018  4.956   1
1  14.29  14.09  0.9050  5.291  3.337  2.699  4.825   1
2  13.84  13.94  0.8955  5.324  3.379  2.259  4.805   1
3  16.14  14.99  0.9034  5.658  3.562  1.355  5.175   1
4  14.38  14.21  0.8951  5.386  3.312  2.462  4.956   1

In [32]:
print(df['A8'].unique())

[1 2 3]


In [33]:
df.describe(include='all')

A1          A2          A3  ...          A6          A7          A8
count  209.000000  209.000000  209.000000  ...  209.000000  209.000000  209.000000
mean    14.845550   14.557943    0.870999  ...    3.707278    5.408971    2.004785
std      2.916545    1.308949    0.023686  ...    1.503657    0.492487    0.817463
min     10.590000   12.410000    0.808100  ...    0.765100    4.519000    1.000000
25%     12.260000   13.450000    0.856700  ...    2.587000    5.045000    1.000000
50%     14.340000   14.290000    0.873500  ...    3.600000    5.224000    2.000000
75%     17.320000   15.730000    0.887900  ...    4.773000    5.877000    3.000000
max     21.180000   17.250000    0.918300  ...    8.456000    6.550000    3.000000

[8 rows x 8 columns]

In [34]:
x=df.drop('A8',axis=1)
y=df['A8']
print(x.head(2))
print(y.head(2))

      A1     A2      A3     A4     A5     A6     A7
0  14.88  14.57  0.8811  5.554  3.333  1.018  4.956
1  14.29  14.09  0.9050  5.291  3.337  2.699  4.825
0    1
1    1
Name: A8, dtype: int64


Splitting to training and testing

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
print(x_train.shape)
print(y_test.shape)

(146, 7)
(63,)


Train the model

In [36]:
from sklearn.neural_network import MLPClassifier

In [37]:
mlp=MLPClassifier(max_iter=500, activation='relu')
mlp

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=500,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

Training


In [38]:
mlp.fit(x_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=500,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

Testing

In [39]:
pred = mlp.predict(x_test)
pred

array([1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 3, 1,
       1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 3, 3, 1, 3, 1, 1, 3, 3, 1,
       1, 3, 3, 1, 1, 1, 3, 1, 3, 3, 1, 1, 3, 1, 1, 1, 1, 1, 1])

Confusion Matrix

In [45]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[18,  0,  1],
       [24,  0,  0],
       [ 6,  0, 14]])

In [47]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           1       0.38      0.95      0.54        19
           2       0.00      0.00      0.00        24
           3       0.93      0.70      0.80        20

    accuracy                           0.51        63
   macro avg       0.44      0.55      0.45        63
weighted avg       0.41      0.51      0.42        63



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
